import { createCanvas, Canvas, CanvasRenderingContext2D } from 'canvas';
import sharp from 'sharp';
import { StandardDataPoint } from '../types';

export class CanvasRenderer {
  private width = 800;
  private height = 480;

  async render(data: StandardDataPoint[]): Promise<Buffer> {
    const canvas = createCanvas(this.width, this.height);
    const ctx = canvas.getContext('2d');

    // Background (White)
    ctx.fillStyle = 'white';
    ctx.fillRect(0, 0, this.width, this.height);

    // Header
    this.drawHeader(ctx);

    // Grid Layout
    this.drawGrid(ctx, data);

    // Footer
    this.drawFooter(ctx);

    // Get raw PNG buffer from canvas
    const rawBuffer = canvas.toBuffer('image/png');

    // Process with Sharp
    // 1. Convert to Grayscale
    // 2. Threshold (128) -> Forces pixels to be pure Black or pure White (1-bit style)
    // 3. Output as PNG with 2 colors (Indexed 1-bit) -> Extremely small size for text/lines
    return await sharp(rawBuffer)
      .grayscale() 
      .threshold(128) 
      .png({ 
        palette: true,
        colors: 2,
        compressionLevel: 9
      })
      .toBuffer();
  }

  private drawHeader(ctx: CanvasRenderingContext2D) {
    ctx.fillStyle = 'black';
    ctx.font = 'bold 30px Arial';
    ctx.fillText('Financial Dashboard', 20, 50);
    
    ctx.textAlign = 'right';
    ctx.font = '20px Arial';
    ctx.fillText(new Date().toLocaleString(), this.width - 20, 50);
    ctx.textAlign = 'left'; // Reset
    
    ctx.lineWidth = 2;
    ctx.beginPath();
    ctx.moveTo(0, 70);
    ctx.lineTo(this.width, 70);
    ctx.stroke();
  }

  private drawGrid(ctx: CanvasRenderingContext2D, data: StandardDataPoint[]) {
    if (data.length === 0) return;

    // Dynamic Layout Calculation
    let cols = 2;
    if (data.length > 8) cols = 4;
    else if (data.length > 4) cols = 3;

    const rows = Math.ceil(data.length / cols);
    
    // Area available: Height (480) - Header(70) - Footer(30) = 380
    const availableHeight = this.height - 100;
    const boxWidth = this.width / cols;
    // Calculate precise row height to fit everything
    const boxHeight = availableHeight / rows;

    // Font scaling based on density
    let labelSize = 24;
    let valueSize = 36;
    let changeSize = 24;
    let padding = 20;

    if (cols >= 3) {
      labelSize = 18;
      valueSize = 28;
      changeSize = 18;
      padding = 15;
    }
    if (cols >= 4) {
      labelSize = 14;
      valueSize = 20;
      changeSize = 14;
      padding = 10;
    }

    data.forEach((item, index) => {
      const col = index % cols;
      const row = Math.floor(index / cols);
      const x = col * boxWidth;
      const y = 70 + (row * boxHeight);

      // Draw divider lines
      ctx.lineWidth = 1;
      ctx.strokeStyle = '#CCCCCC';
      ctx.strokeRect(x, y, boxWidth, boxHeight);

      // Vertical positioning (centered relative to box height)
      // Total content height approx: label + gap + value + gap + change
      // e.g. 20 + 10 + 28 + 10 + 18 = ~86px
      const contentHeight = labelSize + valueSize + changeSize + 20; 
      const startY = y + (boxHeight - contentHeight) / 2 + labelSize;

      // Label
      ctx.fillStyle = '#333333';
      ctx.font = `bold ${labelSize}px Arial`;
      ctx.fillText(item.label, x + padding, startY);

      // Value
      ctx.fillStyle = 'black';
      ctx.font = `bold ${valueSize}px Arial`;
      let valStr = item.value.toString();
      if (typeof item.value === 'number') {
        valStr = item.value.toLocaleString(undefined, { maximumFractionDigits: 2 });
      }
      ctx.fillText(`${valStr} ${item.unit || ''}`, x + padding, startY + valueSize + 5);

      // Change
      if (item.changePercent !== undefined) {
        const isPositive = item.changePercent >= 0;
        const changeStr = `${isPositive ? '+' : ''}${item.changePercent.toFixed(2)}%`;
        
        ctx.font = `${changeSize}px Arial`;
        const arrow = isPositive ? '▲' : '▼';
        ctx.fillText(`${arrow} ${changeStr}`, x + padding, startY + valueSize + changeSize + 10);
      }
    });
  }

  private drawFooter(ctx: CanvasRenderingContext2D) {
    const y = this.height - 10;
    ctx.fillStyle = 'gray';
    ctx.font = '12px Arial';
    ctx.textAlign = 'left';
    ctx.fillText('Generated by Node.js Finance API', 10, y);
  }
}
